---
title: "Linear Modeling in R: Predicting Condominium Sale Prices"
author: "Yunsang Hwang"
date: "2020년 4월 24일"
output: html_document
---



read library
```{r}
library(readr)
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
library(magrittr)
library(broom)
library(tidyr)
library(purrr)
```
This property sales data is [publicly available]
(https://www1.nyc.gov/site/finance/taxes/property-rolling-sales-data.page) and contains sales records from a twelve-month period (April 2019 - March 2020). 
```{r}
NYC_property_sales <- read_csv("NYC_property_sales.csv")
glimpse(NYC_property_sales)
```

```{r}
NYC_condos <- NYC_property_sales %>% 
  filter(building_class_at_time_of_sale == "R4")
```


```{r}
ggplot(data = NYC_condos, aes(x = gross_square_feet, y = sale_price)) +
  geom_point(aes(color = borough), alpha = 0.3) +
  scale_y_continuous(labels = scales::comma, limits = c(0, 75000000)) +
  xlim(0, 10000) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(title = "Condominium Sale Price in NYC Generally Increase with Size",
       x = "Size(Gross Square Feet)",
       y = "Sale price (USD)")
```

```{r}
ggplot(data = NYC_condos, 
       aes(x = gross_square_feet, y = sale_price)) +
  geom_point(aes(color = borough), alpha = 0.3) +
  scale_y_continuous(labels = scales::comma, limits = c(0, 20000000)) +
  xlim(0, 5000) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(title = "Condominium Sale Price in NYC Generally Increases with Size",
       x = "Size (Gross Square Feet)",
       y = "Sale Price (USD)")
```

```{r}
ggplot(data = NYC_condos, 
       aes(x = gross_square_feet, y = sale_price)) +
  geom_point(alpha = 0.3) +
  facet_wrap(~ borough, scales = "free", ncol = 2) +
  scale_y_continuous(labels = scales::comma) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(title = "Condominium Sale Price in NYC Generally Increases with Size",
       x = "Size (Gross Square Feet)",
       y = "Sale Price (USD)")
```

```{r}
NYC_condos %>%
  arrange(desc(sale_price)) %>%
  head
```

```{r}
NYC_condos_original <- NYC_condos
```

```{r}
NYC_condos <- NYC_condos %>% 
  filter(address != "165 East 66th St, Resi")
```

```{r}
NYC_condos %>% 
  filter(borough == "Brooklyn") %>% 
  arrange(desc(sale_price))
```

```{r}
multi_unit_sales <- NYC_condos %>%
  group_by(sale_price, sale_date) %>%
  filter(n() >=3) %>%
  arrange(desc(sale_price))
```

```{r}
NYC_condos <- NYC_condos %>%
  group_by(sale_price, sale_date) %>%
  filter(n() <=2) %>%
  ungroup()
```

```{r}
NYC_condos_lm <- lm(sale_price ~ gross_square_feet, data = NYC_condos)
summary(NYC_condos_lm)
```

```{r}
NYC_condos_original_lm  <- lm(sale_price ~ gross_square_feet, data = NYC_condos_original)  
summary(NYC_condos_original_lm)
```

```{r}
ggplot(data = NYC_condos, 
       aes(x = gross_square_feet, y = sale_price)) +
  geom_point(alpha = 0.3) +
  facet_wrap(~ borough, scales = "free", ncol = 2) +
  scale_y_continuous(labels = scales::comma) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(title = "Condominium Sale Price in NYC Generally Increases with Size",
       x = "Size (Gross Square Feet)",
       y = "Sale Price (USD)")
```

```{r}
NYC_nested <- NYC_condos %>%
  group_by(borough) %>%
  nest()
print(NYC_nested)
```

```{r}
head(NYC_nested$data[[3]])
```


```{r}
NYC_coefficients <- NYC_condos %>% 
  group_by(borough) %>% 
  nest() %>% 
  mutate(linear_model = map(.x = data, 
                            .f = ~lm(sale_price ~ gross_square_feet, 
                                     data = .)))
print(NYC_coefficients)
```

```{r}
summary(NYC_coefficients$linear_model[[3]])
```

```{r}
NYC_coefficients <- NYC_condos %>% 
  group_by(borough) %>% 
  nest() %>% 
  mutate(linear_model = map(.x = data, 
                            .f = ~lm(sale_price ~ gross_square_feet, 
                                     data = .))) %>%
  mutate(tidy_coefficients = map(.x = linear_model, 
                                 .f = tidy, 
                                 conf.int = TRUE))
NYC_coefficients

print(NYC_coefficients$tidy_coefficients[[3]])
```

```{r}
NYC_coefficients_tidy <- NYC_coefficients %>% 
  select(borough, tidy_coefficients) %>% 
  unnest(cols = tidy_coefficients)
print(NYC_coefficients_tidy)
```

```{r}
NYC_slope <- NYC_coefficients_tidy %>%   
  filter(term == "gross_square_feet") %>% 
  arrange(estimate)
print(NYC_slope)
```

```{r}
NYC_summary_stats <- NYC_condos %>% 
  group_by(borough) %>% 
  nest() %>% 
  mutate(linear_model = map(.x = data, 
                            .f = ~lm(sale_price ~ gross_square_feet, 
                                     data = .))) %>%
  mutate(tidy_summary_stats = map(.x = linear_model,
                                  .f = glance))
print(NYC_summary_stats)
```

```{r}
NYC_summary_stats_tidy <- NYC_summary_stats %>% 
  select(borough, tidy_summary_stats) %>% 
  unnest(cols = tidy_summary_stats) %>% 
  arrange(r.squared)
print(NYC_summary_stats_tidy)
```


